---
title: "Linear regression with a two-level factor explanatory variable"
source: Rmd
objectives:
- Use the ggplot2 package to explore the relationship between a continuous variable
  and a two-level factor variable.
- Use the lm command to fit a simple linear regression with a two-level factor explanatory
  variable.
- Use the jtools package to interpret the model output.
- Use the jtools and ggplot2 packages to visualise the resulting model.
keypoints: DEF
questions: GHI
teaching: 10
execises: 10
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
source("../bin/obtain_data.R")
knitr_fig_path("03-")
library(ggplot2)
library(dplyr)
library(tidyr)
library(jtools)
```

> ## Exercise  
> You have been asked to model the relationship between average systolic
> blood pressure and physical activity in the NHANES data. Use the ggplot2
> package to create an exploratory plot, 
> ensuring that it includes the following elements:  
> 1. Average Systolic Blood Pressure (`BPSysAve`) on the y-axis and physical activity (`PhysActive`) on the x-axis, from the NHANES data.  
> 2. This data shown as a violin plot.  
> 3. The y-axis labelled as "Average Systolic Blood Pressure" and the x-axis labelled as "Physically Active".
>
> > ## Solution
> > 
> > ```{r, warning = FALSE}
> > dat %>%
> >   drop_na(c("PhysActive", "BPSysAve")) %>%
> >   ggplot(., aes(x=PhysActive, y=BPSysAve)) +
> >   geom_violin() +
> >   stat_summary(fun = "mean", size = 0.2) +
> >   stat_summary(fun.data = "mean_cl_normal", geom="errorbar", width=0.2) +
> >   xlab("Physically Active")
> > ```
> {: .solution}
{: .challenge}

> ## Exercise  
> 1. Using the `lm()` command, fit a simple linear regression of Average 
> Systolic Blood Pressure (`BPSysAve`)  
> as a function of physical activity (`PhysActive`). Name this `lm` 
> object `BPSysAve_PhysActive_lm`.  
> 2. Using the `summ()` function from the `jtools` package,
> answer the following questions:
>   
> A) What average systolic blood pressure does the model predict, 
> on average,
> for an individual who is characterised as not physically active?  
> B) By how much is average systolic blood pressure expected to change, 
> on average, for a physically active individual?  
> C) Given these two values and the names of the response and explanatory
> variables, how can the general equation $E(y) = \beta_0 + {\beta}_1 
> \times x$ be adapted to represent this model?
> 
> > ## Solution
> > 
> > ```{r}
> > BPSysAve_PhysActive_lm <- lm(BPSysAve ~ PhysActive, data = dat)
> > 
> > summ(BPSysAve_PhysActive_lm, confint = TRUE, digits=3)
> > ```
> > 
> > A) 122.892  
> > B) Decrease by 5.002  
> > C) $E(\text{BPSysAve}) = 122.892 - 5.002 \times \text{PhysActive}$, 
> > where $\text{PhysActive} = 0$ if an individual is not physically active
> > and $\text{PhysActive} = 1$ if an individual is physically active. 
> {: .solution}
{: .challenge}

> ## Exercise  
> Use the `jtools` package to visualise the model of `BPSysAve` as a 
> function of `PhysActive`.  
> Ensure that the x-axis is labelled as "Physically active" and the y-axis
> is labelled as "Average Systolic Blood Pressure".
> How does this plot relate to the output given by `summ`?
>
> > ## Solution
> > 
> > ```{r}
> > effect_plot(BPSysAve_PhysActive_lm, pred = PhysActive,
> > plot.points = TRUE, jitter = 0.3, point.alpha = 0.1) +
> >   xlab("Physically Active") +
> >   ylab("Average Systolic Blood Pressure")
> > ```
> > 
> > This plot shows the mean estimates for `BPSysAve` for the two groups, 
> > alongside their 95% confidence intervals. The mean estimates are 
> > represented by the `Intercept` for the non-physically active group and 
> > by `Intercept` + `PhysActiveYes` for the physically active group. 
> {: .solution}
{: .challenge}




