---
source: Rmd
title: "Linear regression with a multi-level factor explanatory variable"
objectives:
  - "Use the ggplot2 package to explore the relationship between a continuous variable and a factor variable with more than two levels."
  - "Use the lm command to fit a simple linear regression with a factor explanatory variable with more than two levels."
  - "Use the jtools package to interpret the model output."
  - "Use the jtools and ggplot2 packages to visualise the resulting model."
keypoints:
  - "DEF"
questions:
  - "GHI"
teaching: 10
execises: 10
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("04-")
```

```{r load data, include=FALSE}
library(ggplot2)
library(jtools)
library(NHANES)
library(dplyr)
library(tidyr)
dat <- NHANES
```

```{r explore Weight vs Depressed}
dat %>%
  drop_na(c("Depressed", "Weight")) %>%
  ggplot(., aes(x=Depressed, y=Weight)) +
  geom_violin() +
  stat_summary(fun = "mean", size = 0.2) +
  stat_summary(fun.data = "mean_cl_normal", geom="errorbar", width=0.2) +
  xlab("Number of days with depressed feelings")
```


```{r Weight vs Depressed model}
Weight_Depressed_lm <- lm(Weight ~ Depressed, data = dat)

summ(Weight_Depressed_lm, confint = TRUE, digits=3)
```

```{r plot weight vs depressed with model}
effect_plot(Weight_Depressed_lm, pred = Depressed) + 
  xlab("Number of days with depressed feelings")
```

